### ISSUE TITLE
Improve 'list commands' Details

### ISSUE THREAD

**Issue by wadeanthony0100** [rit-sse/hubot#9]
`[bot name]` DM's a long list of commands, many of which are not self-explanatory. This could be improved by adding a description to each one, providing some detail of the command's function.

**Comment by weswigham** [comment]
We used to have a webpage it would tell you do go to that had descriptions, precisely because of this wall of text problem, afaik >.>

**Comment by bbesmanoff** [comment]
Hubot scripts, when properly formatted, have help.  DMing `help` gives those, but not the ids for enable/disable

-----Original Message-----

**Comment by kristenmills** [comment]
@weswigham http://web.ad.sofse.org:8765/zoidberg/help

And what brian says.

**Comment by weswigham** [comment]
aaayyyy, it still exists. Nice. Does the bot tell people about it in the reported help message? It probably should. We can enhance it with links to the command source and references to its ID.

**Comment by kristenmills** [comment]
I forgot to put it back in. I took it out because I didn't want people going to the wrong place then never put it back.

**Comment by weswigham** [comment]
:+1:

**Comment by kristenmills** [comment]
Actually what could be cool is a more organized help instead list commands. It's not how hubot does it, but if you use listener metadata to store help text, we could get rid of `list commands` and the same functionality plus what wade wants can be a part of help.
